import { Memory } from "@/domain/entities/memory.ts";
import { Embedding } from "@/domain/entities/embedding.ts";

/**
 * Supported similarity metrics for vector search operations.
 *
 * Each metric has different mathematical properties:
 * - cosine: Measures angle between vectors, normalized to [-1, 1]
 * - euclidean: Measures geometric distance in n-dimensional space
 * - dot: Inner product of vectors, sensitive to magnitude
 */
export type SimilarityMetric = "cosine" | "euclidean" | "dot";

/**
 * Result from vector similarity search with explicit distance/similarity scoring.
 *
 * Provides both raw distance from the underlying vector index and normalized
 * similarity scores to avoid ambiguity across different backend implementations.
 */
export interface SimilarResult {
  /** The Memory object that matched the similarity search */
  memory: Memory;

  /**
   * Raw distance from the vector index (lower is better).
   * - cosine distance: 0.0 (identical) to 2.0 (opposite)
   * - euclidean distance: 0.0 (identical) to infinity
   * - dot distance: negative infinity to positive infinity
   */
  distance?: number;

  /**
   * Normalized similarity score (higher is better).
   * Always in range [0.0, 1.0] where:
   * - 1.0 = identical vectors
   * - 0.5 = moderate similarity
   * - 0.0 = maximum dissimilarity
   */
  similarity: number;
}

/**
 * Repository interface for Memory persistence operations.
 *
 * Provides database-agnostic abstraction for storing and retrieving Memory objects
 * with full multi-tenant isolation. This interface can be implemented by various
 * database backends including PostgreSQL, DuckDB, or vector stores.
 *
 * @example
 * ```typescript
 * const repository: MemoryRepository = new PostgresMemoryRepository(client);
 * await repository.save(memory, tenantId);
 * const similar = await repository.findSimilar(embedding, 0.8, tenantId);
 * ```
 */
export interface MemoryRepository {
  /**
   * Persist a Memory object to the repository.
   *
   * @param memory - The Memory object to save, including all related entities
   * @param tenantId - UUID identifying the tenant for multi-tenant isolation
   * @throws {ValidationError} When memory fails domain validation
   * @throws {DatabaseError} When persistence operation fails
   */
  save(memory: Memory, tenantId: string): Promise<void>;

  /**
   * Retrieve a Memory by its unique identifier.
   *
   * @param id - The unique identifier of the memory
   * @param tenantId - UUID identifying the tenant for access control
   * @returns The Memory object if found, null otherwise
   */
  findById(id: string, tenantId: string): Promise<Memory | null>;

  /**
   * Find a Memory by its content hash for deduplication.
   *
   * @param hash - The content hash generated by Memory.generateContentHash()
   * @param tenantId - UUID identifying the tenant for access control
   * @returns The Memory object if found, null otherwise
   */
  findByContentHash(hash: string, tenantId: string): Promise<Memory | null>;

  /**
   * Find semantically similar memories using vector similarity search.
   *
   * Implements the "Splashback" feature by finding memories with similarity
   * scores above the specified threshold. Returns both raw distance and normalized
   * similarity to provide maximum transparency across different vector backends.
   *
   * **IMPORTANT**: Query embedding and stored embeddings must be generated by the
   * same model and have identical dimensions for meaningful comparisons. Mixing
   * embeddings from different models (e.g., OpenAI text-embedding-3-small vs
   * Ollama nomic-embed-text) will produce meaningless results.
   *
   * @param embedding - The embedding vector to compare against (must match stored model)
   * @param threshold - Minimum similarity threshold in range [0.0, 1.0] (higher = more similar)
   * @param tenantId - UUID identifying the tenant for access control
   * @param limit - Maximum number of results to return (default: 10)
   * @param metric - Vector similarity metric to use (default: "cosine")
   * @returns Array of similar memories with distance/similarity scores, ordered by relevance (best first)
   * @throws {ValidationError} When embedding dimensions don't match stored embeddings
   * @throws {DatabaseError} When vector search operation fails
   */
  findSimilar(
    embedding: Embedding,
    threshold: number,
    tenantId: string,
    limit?: number,
    metric?: SimilarityMetric,
  ): Promise<ReadonlyArray<SimilarResult>>;

  /**
   * Search memories using full-text search on content.
   *
   * @param query - The search query string
   * @param tenantId - UUID identifying the tenant for access control
   * @param limit - Maximum number of results to return (default: 50)
   * @returns Array of memories matching the search query
   */
  search(query: string, tenantId: string, limit?: number): Promise<Memory[]>;

  /**
   * Retrieve all memories for a tenant with pagination support.
   *
   * @param tenantId - UUID identifying the tenant for access control
   * @param limit - Maximum number of results to return (default: 100)
   * @param offset - Number of records to skip for pagination (default: 0)
   * @returns Array of memories ordered by creation date (newest first)
   */
  findAll(tenantId: string, limit?: number, offset?: number): Promise<Memory[]>;

  /**
   * Delete a Memory from the repository.
   *
   * @param id - The unique identifier of the memory to delete
   * @param tenantId - UUID identifying the tenant for access control
   * @returns True if the memory was deleted, false if not found
   */
  delete(id: string, tenantId: string): Promise<boolean>;
}
